name: Publish Docker Image
on:
  workflow_dispatch:   # allows manual trigger from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          PYTHONPATH=. pytest -q

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/unraid-watcher:latest

